### ISSUE TITLE
Files are in Word

### ISSUE THREAD

**Issue by sneumann** [c-ruttkies/MetFragTraining#1]
Hi, files can be converted to Markdown for better editing and versioning with 
`pandoc -w markdown_github --extract-media=. -o MetFrag\ hands-on\ manual.md MetFrag\ hands-on\ manual.docx`
Shall I create a pull request to eventually replace the docx ? @meier-rene, your opinion ?
Yours, Steffen

**Comment by meier-rene** [comment]
Yesterday we thought about possibilities to create this documents in a more repo friendly manner. Markdown would be repo friendly, but is it also rich enough or is it too limited to create presentation ready documents and can we export to pdf? Lets try it!

**Comment by sneumann** [comment]
First attempt in 2ba4f46f58d64471e1c069d826726212fc4c3ac8, 
resulting in https://github.com/c-ruttkies/MetFragTraining/blob/master/MetFrag%20hands-on%20manual.md
