### ISSUE TITLE
Add Landingpage link

### ISSUE THREAD

**Issue by sneumann** [c-ruttkies/MetFragTraining#2]
For some examples, we could add a LandingPage link, 
so people start already with a usable input spectrum. 
Or is the cut&paste variant more instructive ?

**Comment by c-ruttkies** [comment]
actually a good idea. will add them to the manuscript. however, I think making people adding the data by themselves to the web tool is a good training for later runs.

**Comment by c-ruttkies** [comment]
added two url links ("go to live demo")
